"""
Food Database for Gestational Diabetes Craving Assistant
=========================================================

This file contains the food recognition database.
Each food maps to its taste categories and typical meal type.

To add new foods, just add them to FOOD_DATABASE below!

Categories: sweet, salty, sour, crunchy, creamy, cold, hot, savory, spicy
Meal types: snack, breakfast, lunch, dinner, dessert
"""

## FOOD DATABASE ## 


FOOD_DATABASE = {
    # ==================== SWEETS & DESSERTS ====================
    "chocolate": {"categories": ["sweet"], "meal_type": "snack"},
    "dark chocolate": {"categories": ["sweet"], "meal_type": "snack"},
    "milk chocolate": {"categories": ["sweet"], "meal_type": "snack"},
    "white chocolate": {"categories": ["sweet"], "meal_type": "snack"},
    "chocolate bar": {"categories": ["sweet"], "meal_type": "snack"},
    "candy": {"categories": ["sweet"], "meal_type": "snack"},
    "gummy bears": {"categories": ["sweet"], "meal_type": "snack"},
    "gummies": {"categories": ["sweet"], "meal_type": "snack"},
    "lollipop": {"categories": ["sweet"], "meal_type": "snack"},
    "skittles": {"categories": ["sweet"], "meal_type": "snack"},
    "m&ms": {"categories": ["sweet"], "meal_type": "snack"},
    "reeses": {"categories": ["sweet"], "meal_type": "snack"},
    "snickers": {"categories": ["sweet"], "meal_type": "snack"},
    "twix": {"categories": ["sweet"], "meal_type": "snack"},
    "kit kat": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    "oreos": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    "oreo": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    
    # Cookies & Baked Sweets
    "cookies": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    "cookie": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    "chocolate chip cookie": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    "sugar cookie": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    "biscuit": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    "biscuits": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    "brownie": {"categories": ["sweet"], "meal_type": "dessert"},
    "brownies": {"categories": ["sweet"], "meal_type": "dessert"},
    "blondie": {"categories": ["sweet"], "meal_type": "dessert"},
    
    # Cakes & Pastries
    "cake": {"categories": ["sweet"], "meal_type": "dessert"},
    "birthday cake": {"categories": ["sweet"], "meal_type": "dessert"},
    "chocolate cake": {"categories": ["sweet"], "meal_type": "dessert"},
    "cheesecake": {"categories": ["sweet", "creamy"], "meal_type": "dessert"},
    "carrot cake": {"categories": ["sweet"], "meal_type": "dessert"},
    "red velvet": {"categories": ["sweet"], "meal_type": "dessert"},
    "cupcake": {"categories": ["sweet"], "meal_type": "dessert"},
    "cupcakes": {"categories": ["sweet"], "meal_type": "dessert"},
    "muffin": {"categories": ["sweet"], "meal_type": "snack"},
    "muffins": {"categories": ["sweet"], "meal_type": "snack"},
    "blueberry muffin": {"categories": ["sweet"], "meal_type": "snack"},
    "donut": {"categories": ["sweet"], "meal_type": "snack"},
    "doughnut": {"categories": ["sweet"], "meal_type": "snack"},
    "donuts": {"categories": ["sweet"], "meal_type": "snack"},
    "croissant": {"categories": ["sweet"], "meal_type": "breakfast"},
    "danish": {"categories": ["sweet"], "meal_type": "breakfast"},
    "cinnamon roll": {"categories": ["sweet"], "meal_type": "snack"},
    "pastry": {"categories": ["sweet"], "meal_type": "snack"},
    "pie": {"categories": ["sweet"], "meal_type": "dessert"},
    "apple pie": {"categories": ["sweet", "hot"], "meal_type": "dessert"},
    "pumpkin pie": {"categories": ["sweet"], "meal_type": "dessert"},
    "pecan pie": {"categories": ["sweet"], "meal_type": "dessert"},
    "tart": {"categories": ["sweet"], "meal_type": "dessert"},
    "strudel": {"categories": ["sweet"], "meal_type": "dessert"},
    
    # Frozen Treats
    "ice cream": {"categories": ["sweet", "cold", "creamy"], "meal_type": "dessert"},
    "icecream": {"categories": ["sweet", "cold", "creamy"], "meal_type": "dessert"},
    "gelato": {"categories": ["sweet", "cold", "creamy"], "meal_type": "dessert"},
    "sorbet": {"categories": ["sweet", "cold"], "meal_type": "dessert"},
    "frozen yogurt": {"categories": ["sweet", "cold", "creamy"], "meal_type": "dessert"},
    "froyo": {"categories": ["sweet", "cold", "creamy"], "meal_type": "dessert"},
    "popsicle": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "ice pop": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "milkshake": {"categories": ["sweet", "cold", "creamy"], "meal_type": "snack"},
    "smoothie": {"categories": ["sweet", "cold", "creamy"], "meal_type": "snack"},
    "slushie": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    
    # Puddings & Creamy Desserts
    "pudding": {"categories": ["sweet", "creamy"], "meal_type": "dessert"},
    "chocolate pudding": {"categories": ["sweet", "creamy"], "meal_type": "dessert"},
    "custard": {"categories": ["sweet", "creamy"], "meal_type": "dessert"},
    "mousse": {"categories": ["sweet", "creamy"], "meal_type": "dessert"},
    "tiramisu": {"categories": ["sweet", "creamy"], "meal_type": "dessert"},
    "panna cotta": {"categories": ["sweet", "creamy"], "meal_type": "dessert"},
    "flan": {"categories": ["sweet", "creamy"], "meal_type": "dessert"},
    "creme brulee": {"categories": ["sweet", "creamy"], "meal_type": "dessert"},
    "whipped cream": {"categories": ["sweet", "creamy"], "meal_type": "snack"},
    
    # ==================== FRUITS ====================
    "fruit": {"categories": ["sweet"], "meal_type": "snack"},
    "fruits": {"categories": ["sweet"], "meal_type": "snack"},
    "apple": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    "apples": {"categories": ["sweet", "crunchy"], "meal_type": "snack"},
    "banana": {"categories": ["sweet"], "meal_type": "snack"},
    "bananas": {"categories": ["sweet"], "meal_type": "snack"},
    "orange": {"categories": ["sweet", "sour"], "meal_type": "snack"},
    "oranges": {"categories": ["sweet", "sour"], "meal_type": "snack"},
    "tangerine": {"categories": ["sweet", "sour"], "meal_type": "snack"},
    "clementine": {"categories": ["sweet", "sour"], "meal_type": "snack"},
    "grapefruit": {"categories": ["sour"], "meal_type": "snack"},
    "lemon": {"categories": ["sour"], "meal_type": "snack"},
    "lime": {"categories": ["sour"], "meal_type": "snack"},
    "berries": {"categories": ["sweet"], "meal_type": "snack"},
    "strawberries": {"categories": ["sweet"], "meal_type": "snack"},
    "strawberry": {"categories": ["sweet"], "meal_type": "snack"},
    "blueberries": {"categories": ["sweet"], "meal_type": "snack"},
    "blueberry": {"categories": ["sweet"], "meal_type": "snack"},
    "raspberries": {"categories": ["sweet", "sour"], "meal_type": "snack"},
    "raspberry": {"categories": ["sweet", "sour"], "meal_type": "snack"},
    "blackberries": {"categories": ["sweet"], "meal_type": "snack"},
    "grapes": {"categories": ["sweet"], "meal_type": "snack"},
    "grape": {"categories": ["sweet"], "meal_type": "snack"},
    "cherries": {"categories": ["sweet"], "meal_type": "snack"},
    "cherry": {"categories": ["sweet"], "meal_type": "snack"},
    "watermelon": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "melon": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "cantaloupe": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "honeydew": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "pineapple": {"categories": ["sweet", "sour"], "meal_type": "snack"},
    "mango": {"categories": ["sweet"], "meal_type": "snack"},
    "mangoes": {"categories": ["sweet"], "meal_type": "snack"},
    "papaya": {"categories": ["sweet"], "meal_type": "snack"},
    "kiwi": {"categories": ["sweet", "sour"], "meal_type": "snack"},
    "peach": {"categories": ["sweet"], "meal_type": "snack"},
    "peaches": {"categories": ["sweet"], "meal_type": "snack"},
    "pear": {"categories": ["sweet"], "meal_type": "snack"},
    "plum": {"categories": ["sweet"], "meal_type": "snack"},
    "apricot": {"categories": ["sweet"], "meal_type": "snack"},
    "pomegranate": {"categories": ["sweet", "sour"], "meal_type": "snack"},
    "coconut": {"categories": ["sweet"], "meal_type": "snack"},
    "passion fruit": {"categories": ["sweet", "sour"], "meal_type": "snack"},
    "dragon fruit": {"categories": ["sweet"], "meal_type": "snack"},
    "fig": {"categories": ["sweet"], "meal_type": "snack"},
    "dates": {"categories": ["sweet"], "meal_type": "snack"},
    "raisins": {"categories": ["sweet"], "meal_type": "snack"},
    "dried fruit": {"categories": ["sweet"], "meal_type": "snack"},
    "fruit salad": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    
    # ==================== SALTY SNACKS ====================
    "chips": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "potato chips": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "tortilla chips": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "doritos": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "cheetos": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "pringles": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "lays": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "crisps": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "pretzels": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "pretzel": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "popcorn": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "crackers": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "cracker": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "goldfish": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "cheez-its": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "rice cakes": {"categories": ["crunchy"], "meal_type": "snack"},
    "trail mix": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    
    # Nuts
    "nuts": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "peanuts": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "peanut": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "almonds": {"categories": ["crunchy"], "meal_type": "snack"},
    "almond": {"categories": ["crunchy"], "meal_type": "snack"},
    "cashews": {"categories": ["crunchy"], "meal_type": "snack"},
    "cashew": {"categories": ["crunchy"], "meal_type": "snack"},
    "walnuts": {"categories": ["crunchy"], "meal_type": "snack"},
    "walnut": {"categories": ["crunchy"], "meal_type": "snack"},
    "pistachios": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "pistachio": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "macadamia": {"categories": ["crunchy"], "meal_type": "snack"},
    "pecans": {"categories": ["crunchy"], "meal_type": "snack"},
    "hazelnuts": {"categories": ["crunchy"], "meal_type": "snack"},
    "mixed nuts": {"categories": ["salty", "crunchy"], "meal_type": "snack"},
    "peanut butter": {"categories": ["salty", "creamy"], "meal_type": "snack"},
    "almond butter": {"categories": ["creamy"], "meal_type": "snack"},
    "nutella": {"categories": ["sweet", "creamy"], "meal_type": "snack"},
    
    # ==================== FAST FOOD & FRIED ====================
    "fries": {"categories": ["salty", "hot", "crunchy"], "meal_type": "snack"},
    "french fries": {"categories": ["salty", "hot", "crunchy"], "meal_type": "snack"},
    "curly fries": {"categories": ["salty", "hot", "crunchy"], "meal_type": "snack"},
    "sweet potato fries": {"categories": ["sweet", "hot", "crunchy"], "meal_type": "snack"},
    "onion rings": {"categories": ["salty", "hot", "crunchy"], "meal_type": "snack"},
    "mozzarella sticks": {"categories": ["salty", "hot", "crunchy", "creamy"], "meal_type": "snack"},
    "cheese sticks": {"categories": ["salty", "hot", "crunchy"], "meal_type": "snack"},
    "jalapeno poppers": {"categories": ["spicy", "hot", "crunchy"], "meal_type": "snack"},
    "chicken nuggets": {"categories": ["savory", "hot", "crunchy"], "meal_type": "snack"},
    "nuggets": {"categories": ["savory", "hot", "crunchy"], "meal_type": "snack"},
    "chicken tenders": {"categories": ["savory", "hot", "crunchy"], "meal_type": "snack"},
    "chicken strips": {"categories": ["savory", "hot", "crunchy"], "meal_type": "snack"},
    "chicken wings": {"categories": ["savory", "hot"], "meal_type": "snack"},
    "wings": {"categories": ["savory", "hot"], "meal_type": "snack"},
    "buffalo wings": {"categories": ["savory", "hot", "spicy"], "meal_type": "snack"},
    "hot wings": {"categories": ["savory", "hot", "spicy"], "meal_type": "snack"},
    "fried chicken": {"categories": ["savory", "hot", "crunchy"], "meal_type": "dinner"},
    "popcorn chicken": {"categories": ["savory", "hot", "crunchy"], "meal_type": "snack"},
    "corn dog": {"categories": ["savory", "hot"], "meal_type": "snack"},
    "hot dog": {"categories": ["savory", "hot"], "meal_type": "lunch"},
    "hotdog": {"categories": ["savory", "hot"], "meal_type": "lunch"},
    
    # ==================== PIZZA & ITALIAN ====================
    "pizza": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "pepperoni pizza": {"categories": ["savory", "hot", "spicy"], "meal_type": "dinner"},
    "cheese pizza": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "margherita": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "pasta": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "spaghetti": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "spaghetti bolognese": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "carbonara": {"categories": ["savory", "hot", "creamy"], "meal_type": "dinner"},
    "alfredo": {"categories": ["savory", "hot", "creamy"], "meal_type": "dinner"},
    "fettuccine": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "penne": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "ravioli": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "lasagna": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "lasagne": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "gnocchi": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "risotto": {"categories": ["savory", "hot", "creamy"], "meal_type": "dinner"},
    "macaroni": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "mac and cheese": {"categories": ["savory", "hot", "creamy"], "meal_type": "dinner"},
    "mac n cheese": {"categories": ["savory", "hot", "creamy"], "meal_type": "dinner"},
    "garlic bread": {"categories": ["savory", "hot", "crunchy"], "meal_type": "snack"},
    "breadsticks": {"categories": ["savory", "hot"], "meal_type": "snack"},
    
    # ==================== BURGERS & SANDWICHES ====================
    "burger": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "hamburger": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "cheeseburger": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "veggie burger": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "bacon burger": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "sandwich": {"categories": ["savory"], "meal_type": "lunch"},
    "sandwiches": {"categories": ["savory"], "meal_type": "lunch"},
    "sub": {"categories": ["savory"], "meal_type": "lunch"},
    "submarine": {"categories": ["savory"], "meal_type": "lunch"},
    "hoagie": {"categories": ["savory"], "meal_type": "lunch"},
    "grilled cheese": {"categories": ["savory", "hot", "creamy"], "meal_type": "lunch"},
    "blt": {"categories": ["savory"], "meal_type": "lunch"},
    "club sandwich": {"categories": ["savory"], "meal_type": "lunch"},
    "panini": {"categories": ["savory", "hot", "crunchy"], "meal_type": "lunch"},
    "wrap": {"categories": ["savory"], "meal_type": "lunch"},
    "wraps": {"categories": ["savory"], "meal_type": "lunch"},
    "quesadilla": {"categories": ["savory", "hot"], "meal_type": "lunch"},
    "gyro": {"categories": ["savory", "hot"], "meal_type": "lunch"},
    "pita": {"categories": ["savory"], "meal_type": "lunch"},
    "falafel": {"categories": ["savory", "hot", "crunchy"], "meal_type": "lunch"},
    "shawarma": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "kebab": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    
    # ==================== MEXICAN ====================
    "tacos": {"categories": ["savory", "spicy"], "meal_type": "dinner"},
    "taco": {"categories": ["savory", "spicy"], "meal_type": "dinner"},
    "burrito": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "burritos": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "nachos": {"categories": ["salty", "crunchy", "hot"], "meal_type": "snack"},
    "enchiladas": {"categories": ["savory", "hot", "spicy"], "meal_type": "dinner"},
    "enchilada": {"categories": ["savory", "hot", "spicy"], "meal_type": "dinner"},
    "tamales": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "churros": {"categories": ["sweet", "hot", "crunchy"], "meal_type": "dessert"},
    "guacamole": {"categories": ["savory", "creamy"], "meal_type": "snack"},
    "salsa": {"categories": ["spicy"], "meal_type": "snack"},
    "queso": {"categories": ["savory", "hot", "creamy"], "meal_type": "snack"},
    
    # ==================== ASIAN ====================
    "sushi": {"categories": ["savory", "cold"], "meal_type": "dinner"},
    "sashimi": {"categories": ["savory", "cold"], "meal_type": "dinner"},
    "ramen": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "pho": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "noodles": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "lo mein": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "chow mein": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "pad thai": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "fried rice": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "rice": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "stir fry": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "curry": {"categories": ["savory", "hot", "spicy"], "meal_type": "dinner"},
    "tikka masala": {"categories": ["savory", "hot", "spicy", "creamy"], "meal_type": "dinner"},
    "butter chicken": {"categories": ["savory", "hot", "creamy"], "meal_type": "dinner"},
    "teriyaki": {"categories": ["savory", "sweet", "hot"], "meal_type": "dinner"},
    "orange chicken": {"categories": ["savory", "sweet", "hot"], "meal_type": "dinner"},
    "general tso": {"categories": ["savory", "sweet", "hot", "spicy"], "meal_type": "dinner"},
    "kung pao": {"categories": ["savory", "hot", "spicy"], "meal_type": "dinner"},
    "spring rolls": {"categories": ["savory", "crunchy"], "meal_type": "snack"},
    "egg rolls": {"categories": ["savory", "hot", "crunchy"], "meal_type": "snack"},
    "dumplings": {"categories": ["savory", "hot"], "meal_type": "snack"},
    "gyoza": {"categories": ["savory", "hot"], "meal_type": "snack"},
    "potstickers": {"categories": ["savory", "hot"], "meal_type": "snack"},
    "dim sum": {"categories": ["savory", "hot"], "meal_type": "snack"},
    "wontons": {"categories": ["savory", "hot"], "meal_type": "snack"},
    "edamame": {"categories": ["salty"], "meal_type": "snack"},
    "miso soup": {"categories": ["savory", "hot"], "meal_type": "snack"},
    "tofu": {"categories": ["savory"], "meal_type": "dinner"},
    
    # ==================== MEAT & PROTEIN ====================
    "steak": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "ribeye": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "filet mignon": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "beef": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "roast beef": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "pot roast": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "meatballs": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "meatloaf": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "chicken": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "grilled chicken": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "roasted chicken": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "rotisserie chicken": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "chicken breast": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "chicken thighs": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "turkey": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "pork": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "pork chops": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "pulled pork": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "ribs": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "bbq ribs": {"categories": ["savory", "hot", "sweet"], "meal_type": "dinner"},
    "bacon": {"categories": ["savory", "salty", "crunchy"], "meal_type": "breakfast"},
    "ham": {"categories": ["savory", "salty"], "meal_type": "lunch"},
    "sausage": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "sausages": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "pepperoni": {"categories": ["savory", "salty", "spicy"], "meal_type": "snack"},
    "salami": {"categories": ["savory", "salty"], "meal_type": "snack"},
    "prosciutto": {"categories": ["savory", "salty"], "meal_type": "snack"},
    "lamb": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "lamb chops": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    
    # ==================== SEAFOOD ====================
    "fish": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "salmon": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "tuna": {"categories": ["savory"], "meal_type": "lunch"},
    "tilapia": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "cod": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "halibut": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "fish and chips": {"categories": ["savory", "hot", "crunchy"], "meal_type": "dinner"},
    "fish sticks": {"categories": ["savory", "hot", "crunchy"], "meal_type": "dinner"},
    "shrimp": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "prawns": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "shrimp scampi": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "lobster": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "crab": {"categories": ["savory"], "meal_type": "dinner"},
    "crab cakes": {"categories": ["savory", "hot", "crunchy"], "meal_type": "dinner"},
    "calamari": {"categories": ["savory", "hot", "crunchy"], "meal_type": "snack"},
    "oysters": {"categories": ["savory", "cold"], "meal_type": "snack"},
    "clams": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "mussels": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "scallops": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    
    # ==================== BREAKFAST ====================
    "pancakes": {"categories": ["sweet", "hot"], "meal_type": "breakfast"},
    "pancake": {"categories": ["sweet", "hot"], "meal_type": "breakfast"},
    "waffles": {"categories": ["sweet", "hot", "crunchy"], "meal_type": "breakfast"},
    "waffle": {"categories": ["sweet", "hot", "crunchy"], "meal_type": "breakfast"},
    "french toast": {"categories": ["sweet", "hot"], "meal_type": "breakfast"},
    "eggs": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "egg": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "scrambled eggs": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "fried egg": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "fried eggs": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "poached eggs": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "eggs benedict": {"categories": ["savory", "hot", "creamy"], "meal_type": "breakfast"},
    "omelette": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "omelet": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "frittata": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "quiche": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "toast": {"categories": ["crunchy"], "meal_type": "breakfast"},
    "avocado toast": {"categories": ["savory", "crunchy"], "meal_type": "breakfast"},
    "bagel": {"categories": ["savory"], "meal_type": "breakfast"},
    "bagels": {"categories": ["savory"], "meal_type": "breakfast"},
    "english muffin": {"categories": ["savory"], "meal_type": "breakfast"},
    "cereal": {"categories": ["sweet", "crunchy"], "meal_type": "breakfast"},
    "oatmeal": {"categories": ["hot"], "meal_type": "breakfast"},
    "oats": {"categories": ["hot"], "meal_type": "breakfast"},
    "granola": {"categories": ["sweet", "crunchy"], "meal_type": "breakfast"},
    "yogurt": {"categories": ["creamy"], "meal_type": "snack"},
    "greek yogurt": {"categories": ["creamy"], "meal_type": "snack"},
    "parfait": {"categories": ["sweet", "creamy"], "meal_type": "snack"},
    "hash browns": {"categories": ["salty", "hot", "crunchy"], "meal_type": "breakfast"},
    "home fries": {"categories": ["salty", "hot"], "meal_type": "breakfast"},
    "breakfast burrito": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    "breakfast sandwich": {"categories": ["savory", "hot"], "meal_type": "breakfast"},
    
    # ==================== SOUPS & SALADS ====================
    "soup": {"categories": ["savory", "hot"], "meal_type": "lunch"},
    "chicken soup": {"categories": ["savory", "hot"], "meal_type": "lunch"},
    "chicken noodle soup": {"categories": ["savory", "hot"], "meal_type": "lunch"},
    "tomato soup": {"categories": ["savory", "hot"], "meal_type": "lunch"},
    "vegetable soup": {"categories": ["savory", "hot"], "meal_type": "lunch"},
    "minestrone": {"categories": ["savory", "hot"], "meal_type": "lunch"},
    "clam chowder": {"categories": ["savory", "hot", "creamy"], "meal_type": "lunch"},
    "chili": {"categories": ["savory", "hot", "spicy"], "meal_type": "dinner"},
    "stew": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "beef stew": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "salad": {"categories": ["savory", "cold"], "meal_type": "lunch"},
    "caesar salad": {"categories": ["savory", "cold"], "meal_type": "lunch"},
    "greek salad": {"categories": ["savory", "cold"], "meal_type": "lunch"},
    "garden salad": {"categories": ["savory", "cold"], "meal_type": "lunch"},
    "cobb salad": {"categories": ["savory", "cold"], "meal_type": "lunch"},
    "chicken salad": {"categories": ["savory", "cold"], "meal_type": "lunch"},
    "tuna salad": {"categories": ["savory", "cold"], "meal_type": "lunch"},
    "pasta salad": {"categories": ["savory", "cold"], "meal_type": "lunch"},
    "potato salad": {"categories": ["savory", "cold"], "meal_type": "lunch"},
    "coleslaw": {"categories": ["savory", "cold"], "meal_type": "lunch"},
    
    # ==================== DAIRY & CHEESE ====================
    "cheese": {"categories": ["savory", "creamy"], "meal_type": "snack"},
    "cheddar": {"categories": ["savory"], "meal_type": "snack"},
    "mozzarella": {"categories": ["savory", "creamy"], "meal_type": "snack"},
    "parmesan": {"categories": ["savory", "salty"], "meal_type": "snack"},
    "brie": {"categories": ["savory", "creamy"], "meal_type": "snack"},
    "cream cheese": {"categories": ["savory", "creamy"], "meal_type": "snack"},
    "cottage cheese": {"categories": ["savory", "creamy"], "meal_type": "snack"},
    "string cheese": {"categories": ["savory"], "meal_type": "snack"},
    "cheese curds": {"categories": ["savory", "crunchy"], "meal_type": "snack"},
    "milk": {"categories": ["creamy"], "meal_type": "snack"},
    "chocolate milk": {"categories": ["sweet", "creamy"], "meal_type": "snack"},
    "butter": {"categories": ["creamy"], "meal_type": "snack"},
    "ice cream sandwich": {"categories": ["sweet", "cold"], "meal_type": "dessert"},
    
    # ==================== DRINKS ====================
    "coffee": {"categories": ["hot"], "meal_type": "snack"},
    "latte": {"categories": ["hot", "creamy"], "meal_type": "snack"},
    "cappuccino": {"categories": ["hot", "creamy"], "meal_type": "snack"},
    "espresso": {"categories": ["hot"], "meal_type": "snack"},
    "mocha": {"categories": ["hot", "sweet", "creamy"], "meal_type": "snack"},
    "iced coffee": {"categories": ["cold"], "meal_type": "snack"},
    "frappuccino": {"categories": ["cold", "sweet", "creamy"], "meal_type": "snack"},
    "tea": {"categories": ["hot"], "meal_type": "snack"},
    "iced tea": {"categories": ["cold"], "meal_type": "snack"},
    "boba": {"categories": ["cold", "sweet"], "meal_type": "snack"},
    "bubble tea": {"categories": ["cold", "sweet"], "meal_type": "snack"},
    "hot chocolate": {"categories": ["hot", "sweet", "creamy"], "meal_type": "snack"},
    "hot cocoa": {"categories": ["hot", "sweet", "creamy"], "meal_type": "snack"},
    "juice": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "orange juice": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "apple juice": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "lemonade": {"categories": ["sweet", "sour", "cold"], "meal_type": "snack"},
    "soda": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "coke": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "sprite": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    "ginger ale": {"categories": ["sweet", "cold"], "meal_type": "snack"},
    
    # ==================== VEGETABLES ====================
    "vegetables": {"categories": ["savory"], "meal_type": "dinner"},
    "veggies": {"categories": ["savory"], "meal_type": "dinner"},
    "broccoli": {"categories": ["savory"], "meal_type": "dinner"},
    "carrots": {"categories": ["savory", "crunchy"], "meal_type": "snack"},
    "carrot": {"categories": ["savory", "crunchy"], "meal_type": "snack"},
    "celery": {"categories": ["crunchy"], "meal_type": "snack"},
    "cucumber": {"categories": ["cold", "crunchy"], "meal_type": "snack"},
    "tomato": {"categories": ["savory"], "meal_type": "snack"},
    "tomatoes": {"categories": ["savory"], "meal_type": "snack"},
    "lettuce": {"categories": ["cold"], "meal_type": "lunch"},
    "spinach": {"categories": ["savory"], "meal_type": "lunch"},
    "kale": {"categories": ["savory"], "meal_type": "lunch"},
    "corn": {"categories": ["sweet", "savory"], "meal_type": "dinner"},
    "corn on the cob": {"categories": ["sweet", "savory", "hot"], "meal_type": "dinner"},
    "peas": {"categories": ["savory"], "meal_type": "dinner"},
    "green beans": {"categories": ["savory"], "meal_type": "dinner"},
    "asparagus": {"categories": ["savory"], "meal_type": "dinner"},
    "zucchini": {"categories": ["savory"], "meal_type": "dinner"},
    "eggplant": {"categories": ["savory"], "meal_type": "dinner"},
    "mushrooms": {"categories": ["savory"], "meal_type": "dinner"},
    "mushroom": {"categories": ["savory"], "meal_type": "dinner"},
    "onion": {"categories": ["savory"], "meal_type": "dinner"},
    "onions": {"categories": ["savory"], "meal_type": "dinner"},
    "peppers": {"categories": ["savory", "crunchy"], "meal_type": "dinner"},
    "bell pepper": {"categories": ["savory", "crunchy"], "meal_type": "dinner"},
    "potato": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "potatoes": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "baked potato": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "mashed potatoes": {"categories": ["savory", "hot", "creamy"], "meal_type": "dinner"},
    "sweet potato": {"categories": ["sweet", "hot"], "meal_type": "dinner"},
    "avocado": {"categories": ["creamy"], "meal_type": "snack"},
    "hummus": {"categories": ["savory", "creamy"], "meal_type": "snack"},
    
    # ==================== MISC ====================
    "bread": {"categories": ["savory"], "meal_type": "snack"},
    "baguette": {"categories": ["savory", "crunchy"], "meal_type": "snack"},
    "sourdough": {"categories": ["savory"], "meal_type": "snack"},
    "rolls": {"categories": ["savory"], "meal_type": "dinner"},
    "dinner rolls": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "naan": {"categories": ["savory", "hot"], "meal_type": "dinner"},
    "tortilla": {"categories": ["savory"], "meal_type": "lunch"},
    "flatbread": {"categories": ["savory"], "meal_type": "lunch"},
    "bruschetta": {"categories": ["savory", "crunchy"], "meal_type": "snack"},
    "crostini": {"categories": ["savory", "crunchy"], "meal_type": "snack"},
}


## CATEGORY KEYWORDS ##
CATEGORY_KEYWORDS = {
    "sweet": ["sweet", "sugary", "dessert"],
    "salty": ["salty", "savory", "umami"],
    "sour": ["sour", "tangy", "tart"],
    "crunchy": ["crunchy", "crispy", "crisp"],
    "creamy": ["creamy", "smooth", "rich"],
    "cold": ["cold", "frozen", "icy", "cool"],
    "hot": ["hot", "warm", "heated"],
    "savory": ["savory", "hearty", "filling"],
    "spicy": ["spicy", "hot", "fiery"],
}

## MEAL TYPE KEYWORDS ##

MEAL_TYPE_KEYWORDS = {
    "snack": ["snack", "bite", "nibble", "munch", "quick bite"],
    "breakfast": ["breakfast", "morning", "brunch"],
    "lunch": ["lunch", "midday", "noon"],
    "dinner": ["dinner", "supper", "evening meal"],
    "dessert": ["dessert", "after dinner", "sweet treat"],
}

## INTENSITY KEYWORDS ##

INTENSITY_KEYWORDS = {
    "high": ["really", "badly", "so much", "dying for", "must have", "desperate", "craving so hard"],
    "low": ["maybe", "kind of", "sort of", "might", "could go for", "wouldn't mind"],
}
