"""
Food Database for Gestational Diabetes Craving Assistant
=========================================================

This file contains the food recognition database.
Each food maps to its taste categories and typical meal type.

To add new foods, just add them to FOOD_DATABASE below!

Categories: sweet, salty, sour, crunchy, creamy, cold, hot, savory, spicy
Meal types: snack, breakfast, lunch, dinner, dessert
"""

## FOOD DATABASE ## 


FOOD_DATABASE = {
    # ==================== SWEETS & DESSERTS ====================
    "chocolate": {"id": 1, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 49, "carbs": 26, "sugar": 24},
    "dark chocolate": {"id": 2, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 23, "carbs": 13, "sugar": 7},
    "milk chocolate": {"id": 3, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 42, "carbs": 30, "sugar": 29},
    "white chocolate": {"id": 4, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 44, "carbs": 29, "sugar": 29},
    "chocolate bar": {"id": 5, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 49, "carbs": 35, "sugar": 30},
    "candy": {"id": 6, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 78, "carbs": 40, "sugar": 32},
    "gummy bears": {"id": 7, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 78, "carbs": 35, "sugar": 25},
    "gummies": {"id": 8, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 78, "carbs": 35, "sugar": 25},
    "lollipop": {"id": 9, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 70, "carbs": 14, "sugar": 11},
    "skittles": {"id": 10, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 70, "carbs": 40, "sugar": 30},
    "m&ms": {"id": 11, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 33, "carbs": 30, "sugar": 25},
    "reeses": {"id": 12, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 47, "carbs": 24, "sugar": 21},
    "snickers": {"id": 13, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 51, "carbs": 33, "sugar": 27},
    "twix": {"id": 14, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 45, "carbs": 34, "sugar": 24},
    "kit kat": {"id": 15, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 52, "carbs": 27, "sugar": 20},
    "oreos": {"id": 16, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 55, "carbs": 25, "sugar": 14},
    "oreo": {"id": 17, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 55, "carbs": 25, "sugar": 14},    
    # Cookies & Baked Sweets
    "cookies": {"id": 18, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 50, "carbs": 22, "sugar": 12},
    "cookie": {"id": 19, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 50, "carbs": 22, "sugar": 12},
    "chocolate chip cookie": {"id": 20, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 52, "carbs": 26, "sugar": 18},
    "sugar cookie": {"id": 21, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 59, "carbs": 28, "sugar": 15},
    "biscuit": {"id": 22, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 70, "carbs": 18, "sugar": 3},
    "biscuits": {"id": 23, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 70, "carbs": 18, "sugar": 3},
    "brownie": {"id": 24, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 48, "carbs": 35, "sugar": 25},
    "brownies": {"id": 25, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 48, "carbs": 35, "sugar": 25},
    "blondie": {"id": 26, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 50, "carbs": 32, "sugar": 22},
    
    # Cakes & Pastries
    "cake": {"id": 27, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 59, "carbs": 40, "sugar": 30},
    "birthday cake": {"id": 28, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 65, "carbs": 55, "sugar": 45},
    "chocolate cake": {"id": 29, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 38, "carbs": 50, "sugar": 35},
    "cheesecake": {"id": 30, "categories": ["sweet", "creamy"], "meal_type": "dessert", "glycemic_index": 32, "carbs": 25, "sugar": 20},
    "carrot cake": {"id": 31, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 37, "carbs": 45, "sugar": 30},
    "red velvet": {"id": 32, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 45, "carbs": 48, "sugar": 35},
    "cupcake": {"id": 33, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 73, "carbs": 35, "sugar": 25},
    "cupcakes": {"id": 34, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 73, "carbs": 35, "sugar": 25},
    "muffin": {"id": 35, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 60, "carbs": 45, "sugar": 25},
    "muffins": {"id": 36, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 60, "carbs": 45, "sugar": 25},
    "blueberry muffin": {"id": 37, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 59, "carbs": 46, "sugar": 26},
    "donut": {"id": 38, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 76, "carbs": 30, "sugar": 15},
    "doughnut": {"id": 39, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 76, "carbs": 30, "sugar": 15},
    "donuts": {"id": 40, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 76, "carbs": 30, "sugar": 15},
    "croissant": {"id": 41, "categories": ["sweet"], "meal_type": "breakfast", "glycemic_index": 67, "carbs": 26, "sugar": 6},
    "danish": {"id": 42, "categories": ["sweet"], "meal_type": "breakfast", "glycemic_index": 59, "carbs": 35, "sugar": 15},
    "cinnamon roll": {"id": 43, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 65, "carbs": 55, "sugar": 30},
    "pastry": {"id": 44, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 60, "carbs": 30, "sugar": 15},
    "pie": {"id": 45, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 50, "carbs": 45, "sugar": 25},
    "apple pie": {"id": 46, "categories": ["sweet", "hot"], "meal_type": "dessert", "glycemic_index": 44, "carbs": 40, "sugar": 20},
    "pumpkin pie": {"id": 47, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 42, "carbs": 35, "sugar": 18},
    "pecan pie": {"id": 48, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 55, "carbs": 60, "sugar": 30},
    "tart": {"id": 49, "categories": ["sweet"], "meal_type": "dessert", "glycemic_index": 55, "carbs": 40, "sugar": 20},
    
    # Frozen Treats
    "ice cream": {"id": 51, "categories": ["sweet", "cold", "creamy"], "meal_type": "dessert", "glycemic_index": 51, "carbs": 30, "sugar": 25},
    "icecream": {"id": 52, "categories": ["sweet", "cold", "creamy"], "meal_type": "dessert", "glycemic_index": 51, "carbs": 30, "sugar": 25},
    "gelato": {"id": 53, "categories": ["sweet", "cold", "creamy"], "meal_type": "dessert", "glycemic_index": 55, "carbs": 25, "sugar": 22},
    "sorbet": {"id": 54, "categories": ["sweet", "cold"], "meal_type": "dessert", "glycemic_index": 80, "carbs": 35, "sugar": 35},
    "frozen yogurt": {"id": 55, "categories": ["sweet", "cold", "creamy"], "meal_type": "dessert", "glycemic_index": 35, "carbs": 24, "sugar": 19},
    "froyo": {"id": 56, "categories": ["sweet", "cold", "creamy"], "meal_type": "dessert", "glycemic_index": 35, "carbs": 24, "sugar": 19},
    "popsicle": {"id": 57, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 65, "carbs": 15, "sugar": 15},
    "ice pop": {"id": 58, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 65, "carbs": 15, "sugar": 15},
    "milkshake": {"id": 59, "categories": ["sweet", "cold", "creamy"], "meal_type": "snack", "glycemic_index": 60, "carbs": 60, "sugar": 50},
    "smoothie": {"id": 60, "categories": ["sweet", "cold", "creamy"], "meal_type": "snack", "glycemic_index": 55, "carbs": 45, "sugar": 35},
    "slushie": {"id": 61, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 65, "carbs": 40, "sugar": 40},
    
    # Puddings & Creamy Desserts
    "pudding": {"id": 62, "categories": ["sweet", "creamy"], "meal_type": "dessert", "glycemic_index": 45, "carbs": 25, "sugar": 20},
    "chocolate pudding": {"id": 63, "categories": ["sweet", "creamy"], "meal_type": "dessert", "glycemic_index": 47, "carbs": 28, "sugar": 22},
    "custard": {"id": 64, "categories": ["sweet", "creamy"], "meal_type": "dessert", "glycemic_index": 40, "carbs": 20, "sugar": 15},
    "mousse": {"id": 65, "categories": ["sweet", "creamy"], "meal_type": "dessert", "glycemic_index": 40, "carbs": 15, "sugar": 12},
    "tiramisu": {"id": 66, "categories": ["sweet", "creamy"], "meal_type": "dessert", "glycemic_index": 55, "carbs": 35, "sugar": 20},
    "panna cotta": {"id": 67, "categories": ["sweet", "creamy"], "meal_type": "dessert", "glycemic_index": 45, "carbs": 15, "sugar": 12},
    "flan": {"id": 68, "categories": ["sweet", "creamy"], "meal_type": "dessert", "glycemic_index": 45, "carbs": 25, "sugar": 25},
    "creme brulee": {"id": 69, "categories": ["sweet", "creamy"], "meal_type": "dessert", "glycemic_index": 45, "carbs": 18, "sugar": 15},
    "whipped cream": {"id": 70, "categories": ["sweet", "creamy"], "meal_type": "snack", "glycemic_index": 30, "carbs": 3, "sugar": 1},
    
    
    # ==================== FRUITS ====================
    "fruit": {"id": 71, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 50, "carbs": 15, "sugar": 10},
    "fruits": {"id": 72, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 50, "carbs": 15, "sugar": 10},
    "apple": {"id": 73, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 36, "carbs": 14, "sugar": 10},
    "apples": {"id": 74, "categories": ["sweet", "crunchy"], "meal_type": "snack", "glycemic_index": 36, "carbs": 14, "sugar": 10},
    "banana": {"id": 75, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 51, "carbs": 23, "sugar": 12},
    "bananas": {"id": 76, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 51, "carbs": 23, "sugar": 12},
    "orange": {"id": 77, "categories": ["sweet", "sour"], "meal_type": "snack", "glycemic_index": 43, "carbs": 11, "sugar": 9},
    "oranges": {"id": 78, "categories": ["sweet", "sour"], "meal_type": "snack", "glycemic_index": 43, "carbs": 11, "sugar": 9},
    "tangerine": {"id": 79, "categories": ["sweet", "sour"], "meal_type": "snack", "glycemic_index": 42, "carbs": 13, "sugar": 11},
    "clementine": {"id": 80, "categories": ["sweet", "sour"], "meal_type": "snack", "glycemic_index": 45, "carbs": 12, "sugar": 9},
    "grapefruit": {"id": 81, "categories": ["sour"], "meal_type": "snack", "glycemic_index": 25, "carbs": 11, "sugar": 7},
    "lemon": {"id": 82, "categories": ["sour"], "meal_type": "snack", "glycemic_index": 20, "carbs": 9, "sugar": 2},
    "lime": {"id": 83, "categories": ["sour"], "meal_type": "snack", "glycemic_index": 20, "carbs": 9, "sugar": 2},
    "berries": {"id": 84, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 25, "carbs": 10, "sugar": 5},
    "strawberries": {"id": 85, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 40, "carbs": 8, "sugar": 5},
    "strawberry": {"id": 86, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 40, "carbs": 8, "sugar": 5},
    "blueberries": {"id": 87, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 53, "carbs": 14, "sugar": 10},
    "blueberry": {"id": 88, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 53, "carbs": 14, "sugar": 10},
    "raspberries": {"id": 89, "categories": ["sweet", "sour"], "meal_type": "snack", "glycemic_index": 26, "carbs": 12, "sugar": 5},
    "raspberry": {"id": 90, "categories": ["sweet", "sour"], "meal_type": "snack", "glycemic_index": 26, "carbs": 12, "sugar": 5},
    "blackberries": {"id": 91, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 25, "carbs": 10, "sugar": 5},
    "grapes": {"id": 92, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 59, "carbs": 18, "sugar": 16},
    "grape": {"id": 93, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 59, "carbs": 18, "sugar": 16},
    "cherries": {"id": 94, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 22, "carbs": 16, "sugar": 13},
    "cherry": {"id": 95, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 22, "carbs": 16, "sugar": 13},
    "watermelon": {"id": 96, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 72, "carbs": 8, "sugar": 6},
    "melon": {"id": 97, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 65, "carbs": 13, "sugar": 12},
    "cantaloupe": {"id": 98, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 65, "carbs": 8, "sugar": 8},
    "honeydew": {"id": 99, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 62, "carbs": 9, "sugar": 8},
    "pineapple": {"id": 100, "categories": ["sweet", "sour"], "meal_type": "snack", "glycemic_index": 59, "carbs": 13, "sugar": 10},
    "mango": {"id": 101, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 51, "carbs": 15, "sugar": 14},
    "mangoes": {"id": 102, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 51, "carbs": 15, "sugar": 14},
    "papaya": {"id": 103, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 60, "carbs": 11, "sugar": 8},
    "kiwi": {"id": 104, "categories": ["sweet", "sour"], "meal_type": "snack", "glycemic_index": 50, "carbs": 15, "sugar": 9},
    "peach": {"id": 105, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 42, "carbs": 10, "sugar": 8},
    "peaches": {"id": 106, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 42, "carbs": 10, "sugar": 8},
    "pear": {"id": 107, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 38, "carbs": 15, "sugar": 10},
    "plum": {"id": 108, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 40, "carbs": 8, "sugar": 7},
    "apricot": {"id": 109, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 34, "carbs": 4, "sugar": 3},
    "pomegranate": {"id": 110, "categories": ["sweet", "sour"], "meal_type": "snack", "glycemic_index": 53, "carbs": 19, "sugar": 14},
    "coconut": {"id": 111, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 42, "carbs": 15, "sugar": 6},
    "passion fruit": {"id": 112, "categories": ["sweet", "sour"], "meal_type": "snack", "glycemic_index": 30, "carbs": 23, "sugar": 11},
    "dragon fruit": {"id": 113, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 37, "carbs": 9, "sugar": 8},
    "fig": {"id": 114, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 61, "carbs": 19, "sugar": 16},
    "dates": {"id": 115, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 62, "carbs": 75, "sugar": 66},
    "raisins": {"id": 116, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 64, "carbs": 79, "sugar": 59},
    "dried fruit": {"id": 117, "categories": ["sweet"], "meal_type": "snack", "glycemic_index": 64, "carbs": 70, "sugar": 55},
    "fruit salad": {"id": 118, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 55, "carbs": 20, "sugar": 15},

    # ==================== SALTY SNACKS ====================
    "chips": {"id": 119, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 70, "carbs": 15, "sugar": 0},
    "potato chips": {"id": 120, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 70, "carbs": 15, "sugar": 0},
    "tortilla chips": {"id": 121, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 72, "carbs": 18, "sugar": 0},
    "doritos": {"id": 122, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 72, "carbs": 18, "sugar": 1},
    "cheetos": {"id": 123, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 74, "carbs": 15, "sugar": 1},
    "pringles": {"id": 124, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 70, "carbs": 15, "sugar": 0},
    "lays": {"id": 125, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 70, "carbs": 15, "sugar": 0},
    "crisps": {"id": 126, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 70, "carbs": 15, "sugar": 0},
    "pretzels": {"id": 127, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 83, "carbs": 23, "sugar": 1},
    "pretzel": {"id": 128, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 83, "carbs": 23, "sugar": 1},
    "popcorn": {"id": 129, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 55, "carbs": 6, "sugar": 0},
    "crackers": {"id": 130, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 67, "carbs": 10, "sugar": 1},
    "cracker": {"id": 131, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 67, "carbs": 10, "sugar": 1},
    "goldfish": {"id": 132, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 65, "carbs": 20, "sugar": 1},
    "cheez-its": {"id": 133, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 70, "carbs": 17, "sugar": 0},
    "rice cakes": {"id": 134, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 82, "carbs": 7, "sugar": 0},
    "trail mix": {"id": 135, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 45, "carbs": 15, "sugar": 10},

    # Nuts
    "nuts": {"id": 136, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 15, "carbs": 5, "sugar": 1},
    "peanuts": {"id": 137, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 13, "carbs": 5, "sugar": 1},
    "peanut": {"id": 138, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 13, "carbs": 5, "sugar": 1},
    "almonds": {"id": 139, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 0, "carbs": 6, "sugar": 1},
    "almond": {"id": 140, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 0, "carbs": 6, "sugar": 1},
    "cashews": {"id": 141, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 22, "carbs": 9, "sugar": 2},
    "cashew": {"id": 142, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 22, "carbs": 9, "sugar": 2},
    "walnuts": {"id": 143, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 15, "carbs": 4, "sugar": 1},
    "walnut": {"id": 144, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 15, "carbs": 4, "sugar": 1},
    "pistachios": {"id": 145, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 18, "carbs": 8, "sugar": 2},
    "pistachio": {"id": 146, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 18, "carbs": 8, "sugar": 2},
    "macadamia": {"id": 147, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 10, "carbs": 4, "sugar": 1},
    "pecans": {"id": 148, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 10, "carbs": 4, "sugar": 1},
    "hazelnuts": {"id": 149, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 15, "carbs": 5, "sugar": 1},
    "mixed nuts": {"id": 150, "categories": ["salty", "crunchy"], "meal_type": "snack", "glycemic_index": 15, "carbs": 6, "sugar": 1},
    "peanut butter": {"id": 151, "categories": ["salty", "creamy"], "meal_type": "snack", "glycemic_index": 14, "carbs": 6, "sugar": 3},
    "almond butter": {"id": 152, "categories": ["creamy"], "meal_type": "snack", "glycemic_index": 0, "carbs": 6, "sugar": 2},
    "nutella": {"id": 153, "categories": ["sweet", "creamy"], "meal_type": "snack", "glycemic_index": 55, "carbs": 21, "sugar": 20},

    # ==================== FAST FOOD & FRIED ====================
    "fries": {"id": 154, "categories": ["salty", "hot"], "meal_type": "snack", "glycemic_index": 75, "carbs": 40, "sugar": 0},
    "french fries": {"id": 155, "categories": ["salty", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 75, "carbs": 40, "sugar": 0},
    "curly fries": {"id": 156, "categories": ["salty", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 75, "carbs": 42, "sugar": 0},
    "sweet potato fries": {"id": 157, "categories": ["sweet", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 50, "carbs": 25, "sugar": 8},
    "onion rings": {"id": 158, "categories": ["salty", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 75, "carbs": 35, "sugar": 4},
    "mozzarella sticks": {"id": 159, "categories": ["salty", "hot", "crunchy", "creamy"], "meal_type": "snack", "glycemic_index": 60, "carbs": 25, "sugar": 1},
    "cheese sticks": {"id": 160, "categories": ["salty", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 60, "carbs": 25, "sugar": 1},
    "jalapeno poppers": {"id": 161, "categories": ["spicy", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 60, "carbs": 20, "sugar": 2},
    "chicken nuggets": {"id": 162, "categories": ["savory", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 46, "carbs": 15, "sugar": 0},
    "nuggets": {"id": 163, "categories": ["savory", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 46, "carbs": 15, "sugar": 0},
    "chicken tenders": {"id": 164, "categories": ["savory", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 50, "carbs": 20, "sugar": 0},
    "chicken strips": {"id": 165, "categories": ["savory", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 50, "carbs": 20, "sugar": 0},
    "chicken wings": {"id": 166, "categories": ["savory", "hot"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "wings": {"id": 167, "categories": ["savory", "hot"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "buffalo wings": {"id": 168, "categories": ["savory", "hot", "spicy"], "meal_type": "snack", "glycemic_index": 5, "carbs": 2, "sugar": 1},
    "hot wings": {"id": 169, "categories": ["savory", "hot", "spicy"], "meal_type": "snack", "glycemic_index": 5, "carbs": 2, "sugar": 1},
    "fried chicken": {"id": 170, "categories": ["savory", "hot", "crunchy"], "meal_type": "dinner", "glycemic_index": 40, "carbs": 15, "sugar": 0},
    "popcorn chicken": {"id": 171, "categories": ["savory", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 46, "carbs": 18, "sugar": 0},
    "corn dog": {"id": 172, "categories": ["savory", "hot"], "meal_type": "snack", "glycemic_index": 60, "carbs": 28, "sugar": 9},
    "hot dog": {"id": 173, "categories": ["savory", "hot"], "meal_type": "lunch", "glycemic_index": 65, "carbs": 22, "sugar": 2},
    "hotdog": {"id": 174, "categories": ["savory", "hot"], "meal_type": "lunch", "glycemic_index": 65, "carbs": 22, "sugar": 2},

    # ==================== PIZZA & ITALIAN ====================
    "pizza": {"id": 175, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 80, "carbs": 35, "sugar": 4},
    "pepperoni pizza": {"id": 176, "categories": ["savory", "hot", "spicy"], "meal_type": "dinner", "glycemic_index": 80, "carbs": 35, "sugar": 4},
    "cheese pizza": {"id": 177, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 80, "carbs": 35, "sugar": 4},
    "margherita": {"id": 178, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 80, "carbs": 34, "sugar": 3},
    "pasta": {"id": 179, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 50, "carbs": 42, "sugar": 2},
    "spaghetti": {"id": 180, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 48, "carbs": 42, "sugar": 2},
    "spaghetti bolognese": {"id": 181, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 48, "carbs": 45, "sugar": 6},
    "carbonara": {"id": 182, "categories": ["savory", "hot", "creamy"], "meal_type": "dinner", "glycemic_index": 45, "carbs": 42, "sugar": 2},
    "alfredo": {"id": 183, "categories": ["savory", "hot", "creamy"], "meal_type": "dinner", "glycemic_index": 45, "carbs": 42, "sugar": 2},
    "fettuccine": {"id": 184, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 50, "carbs": 42, "sugar": 2},
    "penne": {"id": 185, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 50, "carbs": 42, "sugar": 2},
    "ravioli": {"id": 186, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 52, "carbs": 40, "sugar": 2},
    "lasagna": {"id": 187, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 47, "carbs": 35, "sugar": 5},
    "lasagne": {"id": 188, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 47, "carbs": 35, "sugar": 5},
    "gnocchi": {"id": 189, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 70, "carbs": 32, "sugar": 1},
    "risotto": {"id": 190, "categories": ["savory", "hot", "creamy"], "meal_type": "dinner", "glycemic_index": 70, "carbs": 45, "sugar": 2},
    "macaroni": {"id": 191, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 50, "carbs": 42, "sugar": 2},
    "mac and cheese": {"id": 192, "categories": ["savory", "hot", "creamy"], "meal_type": "dinner", "glycemic_index": 64, "carbs": 50, "sugar": 6},
    "mac n cheese": {"id": 193, "categories": ["savory", "hot", "creamy"], "meal_type": "dinner", "glycemic_index": 64, "carbs": 50, "sugar": 6},
    "garlic bread": {"id": 194, "categories": ["savory", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 72, "carbs": 20, "sugar": 1},
    "breadsticks": {"id": 195, "categories": ["savory", "hot"], "meal_type": "snack", "glycemic_index": 70, "carbs": 15, "sugar": 1},

    # ==================== BURGERS & SANDWICHES ====================
    "burger": {"id": 196, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 70, "carbs": 30, "sugar": 6},
    "hamburger": {"id": 197, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 70, "carbs": 30, "sugar": 6},
    "cheeseburger": {"id": 198, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 70, "carbs": 30, "sugar": 6},
    "veggie burger": {"id": 199, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 60, "carbs": 35, "sugar": 5},
    "bacon burger": {"id": 200, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 70, "carbs": 30, "sugar": 6},
    "sandwich": {"id": 201, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 65, "carbs": 35, "sugar": 4},
    "sandwiches": {"id": 202, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 65, "carbs": 35, "sugar": 4},
    "sub": {"id": 203, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 70, "carbs": 45, "sugar": 6},
    "submarine": {"id": 204, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 70, "carbs": 45, "sugar": 6},
    "hoagie": {"id": 205, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 70, "carbs": 45, "sugar": 6},
    "grilled cheese": {"id": 206, "categories": ["savory", "hot", "creamy"], "meal_type": "lunch", "glycemic_index": 70, "carbs": 30, "sugar": 3},
    "blt": {"id": 207, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 65, "carbs": 30, "sugar": 4},
    "club sandwich": {"id": 208, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 65, "carbs": 35, "sugar": 4},
    "panini": {"id": 209, "categories": ["savory", "hot", "crunchy"], "meal_type": "lunch", "glycemic_index": 70, "carbs": 35, "sugar": 3},
    "wrap": {"id": 210, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 60, "carbs": 25, "sugar": 2},
    "wraps": {"id": 211, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 60, "carbs": 25, "sugar": 2},
    "quesadilla": {"id": 212, "categories": ["savory", "hot"], "meal_type": "lunch", "glycemic_index": 65, "carbs": 30, "sugar": 2},
    "gyro": {"id": 213, "categories": ["savory", "hot"], "meal_type": "lunch", "glycemic_index": 60, "carbs": 35, "sugar": 4},
    "pita": {"id": 214, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 60, "carbs": 35, "sugar": 2},
    "falafel": {"id": 215, "categories": ["savory", "hot", "crunchy"], "meal_type": "lunch", "glycemic_index": 45, "carbs": 25, "sugar": 3},
    "shawarma": {"id": 216, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 60, "carbs": 35, "sugar": 4},
    "kebab": {"id": 217, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 45, "carbs": 10, "sugar": 2},

    # ==================== MEXICAN ====================
    "tacos": {"id": 218, "categories": ["savory", "spicy"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 20, "sugar": 2},
    "taco": {"id": 219, "categories": ["savory", "spicy"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 20, "sugar": 2},
    "burrito": {"id": 220, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 65, "carbs": 60, "sugar": 4},
    "burritos": {"id": 221, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 65, "carbs": 60, "sugar": 4},
    "nachos": {"id": 222, "categories": ["salty", "crunchy", "hot"], "meal_type": "snack", "glycemic_index": 70, "carbs": 40, "sugar": 2},
    "enchiladas": {"id": 223, "categories": ["savory", "hot", "spicy"], "meal_type": "dinner", "glycemic_index": 60, "carbs": 45, "sugar": 4},
    "enchilada": {"id": 224, "categories": ["savory", "hot", "spicy"], "meal_type": "dinner", "glycemic_index": 60, "carbs": 45, "sugar": 4},
    "tamales": {"id": 225, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 60, "carbs": 30, "sugar": 2},
    "churros": {"id": 226, "categories": ["sweet", "hot", "crunchy"], "meal_type": "dessert", "glycemic_index": 75, "carbs": 30, "sugar": 15},
    "guacamole": {"id": 227, "categories": ["savory", "creamy"], "meal_type": "snack", "glycemic_index": 15, "carbs": 8, "sugar": 1},
    "salsa": {"id": 228, "categories": ["spicy"], "meal_type": "snack", "glycemic_index": 20, "carbs": 7, "sugar": 4},
    "queso": {"id": 229, "categories": ["savory", "hot", "creamy"], "meal_type": "snack", "glycemic_index": 45, "carbs": 5, "sugar": 2},

    # ==================== ASIAN ====================
    "sushi": {"id": 230, "categories": ["savory", "cold"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 45, "sugar": 6},
    "sashimi": {"id": 231, "categories": ["savory", "cold"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "ramen": {"id": 232, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 50, "carbs": 55, "sugar": 3},
    "pho": {"id": 233, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 60, "carbs": 50, "sugar": 5},
    "noodles": {"id": 234, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 45, "sugar": 2},
    "lo mein": {"id": 235, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 45, "sugar": 4},
    "chow mein": {"id": 236, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 45, "sugar": 4},
    "pad thai": {"id": 237, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 60, "carbs": 60, "sugar": 15},
    "fried rice": {"id": 238, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 65, "carbs": 45, "sugar": 2},
    "rice": {"id": 239, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 72, "carbs": 45, "sugar": 0},
    "stir fry": {"id": 240, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 40, "carbs": 15, "sugar": 5},
    "curry": {"id": 241, "categories": ["savory", "hot", "spicy"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 25, "sugar": 5},
    "tikka masala": {"id": 242, "categories": ["savory", "hot", "spicy", "creamy"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 20, "sugar": 7},
    "butter chicken": {"id": 243, "categories": ["savory", "hot", "creamy"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 15, "sugar": 6},
    "teriyaki": {"id": 244, "categories": ["savory", "sweet", "hot"], "meal_type": "dinner", "glycemic_index": 60, "carbs": 20, "sugar": 18},
    "orange chicken": {"id": 245, "categories": ["savory", "sweet", "hot"], "meal_type": "dinner", "glycemic_index": 60, "carbs": 30, "sugar": 22},
    "general tso": {"id": 246, "categories": ["savory", "sweet", "hot", "spicy"], "meal_type": "dinner", "glycemic_index": 60, "carbs": 30, "sugar": 22},
    "kung pao": {"id": 247, "categories": ["savory", "hot", "spicy"], "meal_type": "dinner", "glycemic_index": 50, "carbs": 20, "sugar": 8},
    "spring rolls": {"id": 248, "categories": ["savory", "crunchy"], "meal_type": "snack", "glycemic_index": 55, "carbs": 20, "sugar": 2},
    "egg rolls": {"id": 249, "categories": ["savory", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 60, "carbs": 25, "sugar": 3},
    "dumplings": {"id": 250, "categories": ["savory", "hot"], "meal_type": "snack", "glycemic_index": 55, "carbs": 30, "sugar": 2},
    "gyoza": {"id": 251, "categories": ["savory", "hot"], "meal_type": "snack", "glycemic_index": 55, "carbs": 30, "sugar": 2},
    "potstickers": {"id": 252, "categories": ["savory", "hot"], "meal_type": "snack", "glycemic_index": 55, "carbs": 30, "sugar": 2},
    "dim sum": {"id": 253, "categories": ["savory", "hot"], "meal_type": "snack", "glycemic_index": 55, "carbs": 30, "sugar": 3},
    "wontons": {"id": 254, "categories": ["savory", "hot"], "meal_type": "snack", "glycemic_index": 60, "carbs": 15, "sugar": 1},
    "edamame": {"id": 255, "categories": ["salty"], "meal_type": "snack", "glycemic_index": 15, "carbs": 10, "sugar": 2},
    "miso soup": {"id": 256, "categories": ["savory", "hot"], "meal_type": "snack", "glycemic_index": 20, "carbs": 7, "sugar": 2},
    "tofu": {"id": 257, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 4, "sugar": 1},

    # ==================== MEAT & PROTEIN ====================
    "steak": {"id": 258, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "ribeye": {"id": 259, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "filet mignon": {"id": 260, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "beef": {"id": 261, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "roast beef": {"id": 262, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "pot roast": {"id": 263, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "meatballs": {"id": 264, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 45, "carbs": 10, "sugar": 2},
    "meatloaf": {"id": 265, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 45, "carbs": 15, "sugar": 6},
    "chicken": {"id": 266, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "grilled chicken": {"id": 267, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "roasted chicken": {"id": 268, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "rotisserie chicken": {"id": 269, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "chicken breast": {"id": 270, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "chicken thighs": {"id": 271, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "turkey": {"id": 272, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "pork": {"id": 273, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "pork chops": {"id": 274, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "pulled pork": {"id": 275, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 45, "carbs": 15, "sugar": 12},
    "ribs": {"id": 276, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 45, "carbs": 15, "sugar": 12},
    "bbq ribs": {"id": 277, "categories": ["savory", "hot", "sweet"], "meal_type": "dinner", "glycemic_index": 50, "carbs": 25, "sugar": 20},
    "bacon": {"id": 278, "categories": ["savory", "salty", "crunchy"], "meal_type": "breakfast", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "ham": {"id": 279, "categories": ["savory", "salty"], "meal_type": "lunch", "glycemic_index": 0, "carbs": 1, "sugar": 1},
    "sausage": {"id": 280, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 28, "carbs": 1, "sugar": 0},
    "sausages": {"id": 281, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 28, "carbs": 1, "sugar": 0},
    "pepperoni": {"id": 282, "categories": ["savory", "salty", "spicy"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "salami": {"id": 283, "categories": ["savory", "salty"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "prosciutto": {"id": 284, "categories": ["savory", "salty"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "lamb": {"id": 285, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "lamb chops": {"id": 286, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},

    # ==================== SEAFOOD ====================
    "fish": {"id": 287, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "salmon": {"id": 288, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "tuna": {"id": 289, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "tilapia": {"id": 290, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "cod": {"id": 291, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "halibut": {"id": 292, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "fish and chips": {"id": 293, "categories": ["savory", "hot", "crunchy"], "meal_type": "dinner", "glycemic_index": 65, "carbs": 40, "sugar": 1},
    "fish sticks": {"id": 294, "categories": ["savory", "hot", "crunchy"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 20, "sugar": 1},
    "shrimp": {"id": 295, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "prawns": {"id": 296, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "shrimp scampi": {"id": 297, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 45, "carbs": 10, "sugar": 1},
    "lobster": {"id": 298, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "crab": {"id": 299, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "crab cakes": {"id": 300, "categories": ["savory", "hot", "crunchy"], "meal_type": "dinner", "glycemic_index": 50, "carbs": 15, "sugar": 2},
    "calamari": {"id": 301, "categories": ["savory", "hot", "crunchy"], "meal_type": "snack", "glycemic_index": 50, "carbs": 18, "sugar": 1},
    "oysters": {"id": 302, "categories": ["savory", "cold"], "meal_type": "snack", "glycemic_index": 0, "carbs": 4, "sugar": 0},
    "clams": {"id": 303, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 3, "sugar": 0},
    "mussels": {"id": 304, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 4, "sugar": 0},
    "scallops": {"id": 305, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 0, "carbs": 3, "sugar": 0},

    # ==================== BREAKFAST ====================
    "pancakes": {"id": 306, "categories": ["sweet", "hot"], "meal_type": "breakfast", "glycemic_index": 67, "carbs": 28, "sugar": 6},
    "pancake": {"id": 307, "categories": ["sweet", "hot"], "meal_type": "breakfast", "glycemic_index": 67, "carbs": 28, "sugar": 6},
    "waffles": {"id": 308, "categories": ["sweet", "hot", "crunchy"], "meal_type": "breakfast", "glycemic_index": 76, "carbs": 30, "sugar": 5},
    "waffle": {"id": 309, "categories": ["sweet", "hot", "crunchy"], "meal_type": "breakfast", "glycemic_index": 76, "carbs": 30, "sugar": 5},
    "french toast": {"id": 310, "categories": ["sweet", "hot"], "meal_type": "breakfast", "glycemic_index": 66, "carbs": 35, "sugar": 12},
    "eggs": {"id": 311, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 0, "carbs": 1, "sugar": 1},
    "egg": {"id": 312, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 0, "carbs": 1, "sugar": 1},
    "scrambled eggs": {"id": 313, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 0, "carbs": 1, "sugar": 1},
    "fried egg": {"id": 314, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 0, "carbs": 1, "sugar": 1},
    "fried eggs": {"id": 315, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 0, "carbs": 1, "sugar": 1},
    "poached eggs": {"id": 316, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 0, "carbs": 1, "sugar": 1},
    "eggs benedict": {"id": 317, "categories": ["savory", "hot", "creamy"], "meal_type": "breakfast", "glycemic_index": 45, "carbs": 20, "sugar": 1},
    "omelette": {"id": 318, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 0, "carbs": 2, "sugar": 1},
    "omelet": {"id": 319, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 0, "carbs": 2, "sugar": 1},
    "frittata": {"id": 320, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 0, "carbs": 5, "sugar": 2},
    "quiche": {"id": 321, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 40, "carbs": 15, "sugar": 2},
    "toast": {"id": 322, "categories": ["crunchy"], "meal_type": "breakfast", "glycemic_index": 75, "carbs": 15, "sugar": 2},
    "avocado toast": {"id": 323, "categories": ["savory", "crunchy"], "meal_type": "breakfast", "glycemic_index": 50, "carbs": 20, "sugar": 2},
    "bagel": {"id": 324, "categories": ["savory"], "meal_type": "breakfast", "glycemic_index": 72, "carbs": 48, "sugar": 6},
    "bagels": {"id": 325, "categories": ["savory"], "meal_type": "breakfast", "glycemic_index": 72, "carbs": 48, "sugar": 6},
    "english muffin": {"id": 326, "categories": ["savory"], "meal_type": "breakfast", "glycemic_index": 70, "carbs": 26, "sugar": 1},
    "cereal": {"id": 327, "categories": ["sweet", "crunchy"], "meal_type": "breakfast", "glycemic_index": 75, "carbs": 30, "sugar": 12},
    "oatmeal": {"id": 328, "categories": ["hot"], "meal_type": "breakfast", "glycemic_index": 55, "carbs": 27, "sugar": 1},
    "oats": {"id": 329, "categories": ["hot"], "meal_type": "breakfast", "glycemic_index": 55, "carbs": 27, "sugar": 1},
    "granola": {"id": 330, "categories": ["sweet", "crunchy"], "meal_type": "breakfast", "glycemic_index": 60, "carbs": 30, "sugar": 14},
    "yogurt": {"id": 331, "categories": ["creamy"], "meal_type": "snack", "glycemic_index": 33, "carbs": 12, "sugar": 12},
    "greek yogurt": {"id": 332, "categories": ["creamy"], "meal_type": "snack", "glycemic_index": 12, "carbs": 6, "sugar": 6},
    "parfait": {"id": 333, "categories": ["sweet", "creamy"], "meal_type": "snack", "glycemic_index": 50, "carbs": 30, "sugar": 20},
    "hash browns": {"id": 334, "categories": ["salty", "hot", "crunchy"], "meal_type": "breakfast", "glycemic_index": 75, "carbs": 25, "sugar": 0},
    "home fries": {"id": 335, "categories": ["salty", "hot"], "meal_type": "breakfast", "glycemic_index": 75, "carbs": 25, "sugar": 0},
    "breakfast burrito": {"id": 336, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 65, "carbs": 35, "sugar": 3},
    "breakfast sandwich": {"id": 337, "categories": ["savory", "hot"], "meal_type": "breakfast", "glycemic_index": 65, "carbs": 30, "sugar": 3},

    # ==================== SOUPS & SALADS ====================
    "soup": {"id": 338, "categories": ["savory", "hot"], "meal_type": "lunch", "glycemic_index": 45, "carbs": 15, "sugar": 2},
    "chicken soup": {"id": 339, "categories": ["savory", "hot"], "meal_type": "lunch", "glycemic_index": 40, "carbs": 10, "sugar": 1},
    "chicken noodle soup": {"id": 340, "categories": ["savory", "hot"], "meal_type": "lunch", "glycemic_index": 45, "carbs": 18, "sugar": 2},
    "tomato soup": {"id": 341, "categories": ["savory", "hot"], "meal_type": "lunch", "glycemic_index": 55, "carbs": 20, "sugar": 10},
    "vegetable soup": {"id": 342, "categories": ["savory", "hot"], "meal_type": "lunch", "glycemic_index": 40, "carbs": 15, "sugar": 4},
    "minestrone": {"id": 343, "categories": ["savory", "hot"], "meal_type": "lunch", "glycemic_index": 45, "carbs": 25, "sugar": 4},
    "clam chowder": {"id": 344, "categories": ["savory", "hot", "creamy"], "meal_type": "lunch", "glycemic_index": 50, "carbs": 18, "sugar": 2},
    "chili": {"id": 345, "categories": ["savory", "hot", "spicy"], "meal_type": "dinner", "glycemic_index": 40, "carbs": 25, "sugar": 5},
    "stew": {"id": 346, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 45, "carbs": 20, "sugar": 3},
    "beef stew": {"id": 347, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 45, "carbs": 20, "sugar": 3},
    "salad": {"id": 348, "categories": ["savory", "cold"], "meal_type": "lunch", "glycemic_index": 15, "carbs": 5, "sugar": 2},
    "caesar salad": {"id": 349, "categories": ["savory", "cold"], "meal_type": "lunch", "glycemic_index": 20, "carbs": 10, "sugar": 2},
    "greek salad": {"id": 350, "categories": ["savory", "cold"], "meal_type": "lunch", "glycemic_index": 15, "carbs": 8, "sugar": 3},
    "garden salad": {"id": 351, "categories": ["savory", "cold"], "meal_type": "lunch", "glycemic_index": 15, "carbs": 5, "sugar": 2},
    "cobb salad": {"id": 352, "categories": ["savory", "cold"], "meal_type": "lunch", "glycemic_index": 15, "carbs": 5, "sugar": 2},
    "chicken salad": {"id": 353, "categories": ["savory", "cold"], "meal_type": "lunch", "glycemic_index": 15, "carbs": 5, "sugar": 2},
    "tuna salad": {"id": 354, "categories": ["savory", "cold"], "meal_type": "lunch", "glycemic_index": 15, "carbs": 5, "sugar": 1},
    "pasta salad": {"id": 355, "categories": ["savory", "cold"], "meal_type": "lunch", "glycemic_index": 50, "carbs": 35, "sugar": 3},
    "potato salad": {"id": 356, "categories": ["savory", "cold"], "meal_type": "lunch", "glycemic_index": 65, "carbs": 25, "sugar": 3},
    "coleslaw": {"id": 357, "categories": ["savory", "cold"], "meal_type": "lunch", "glycemic_index": 45, "carbs": 15, "sugar": 12},

    # ==================== DAIRY & CHEESE ====================
    "cheese": {"id": 358, "categories": ["savory", "creamy"], "meal_type": "snack", "glycemic_index": 0, "carbs": 1, "sugar": 0},
    "cheddar": {"id": 359, "categories": ["savory"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "mozzarella": {"id": 360, "categories": ["savory", "creamy"], "meal_type": "snack", "glycemic_index": 0, "carbs": 1, "sugar": 0},
    "parmesan": {"id": 361, "categories": ["savory", "salty"], "meal_type": "snack", "glycemic_index": 0, "carbs": 3, "sugar": 0},
    "brie": {"id": 362, "categories": ["savory", "creamy"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "cream cheese": {"id": 363, "categories": ["savory", "creamy"], "meal_type": "snack", "glycemic_index": 0, "carbs": 1, "sugar": 1},
    "cottage cheese": {"id": 364, "categories": ["savory", "creamy"], "meal_type": "snack", "glycemic_index": 10, "carbs": 3, "sugar": 3},
    "string cheese": {"id": 365, "categories": ["savory"], "meal_type": "snack", "glycemic_index": 0, "carbs": 1, "sugar": 0},
    "cheese curds": {"id": 366, "categories": ["savory", "crunchy"], "meal_type": "snack", "glycemic_index": 0, "carbs": 1, "sugar": 0},
    "milk": {"id": 367, "categories": ["creamy"], "meal_type": "snack", "glycemic_index": 30, "carbs": 12, "sugar": 12},
    "chocolate milk": {"id": 368, "categories": ["sweet", "creamy"], "meal_type": "snack", "glycemic_index": 45, "carbs": 26, "sugar": 24},
    "butter": {"id": 369, "categories": ["creamy"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "ice cream sandwich": {"id": 370, "categories": ["sweet", "cold"], "meal_type": "dessert", "glycemic_index": 65, "carbs": 35, "sugar": 20},

    # ==================== DRINKS ====================
    "coffee": {"id": 371, "categories": ["hot"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "latte": {"id": 372, "categories": ["hot", "creamy"], "meal_type": "snack", "glycemic_index": 30, "carbs": 15, "sugar": 13},
    "cappuccino": {"id": 373, "categories": ["hot", "creamy"], "meal_type": "snack", "glycemic_index": 30, "carbs": 12, "sugar": 10},
    "espresso": {"id": 374, "categories": ["hot"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "mocha": {"id": 375, "categories": ["hot", "sweet", "creamy"], "meal_type": "snack", "glycemic_index": 45, "carbs": 30, "sugar": 25},
    "iced coffee": {"id": 376, "categories": ["cold"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "frappuccino": {"id": 377, "categories": ["cold", "sweet", "creamy"], "meal_type": "snack", "glycemic_index": 60, "carbs": 50, "sugar": 45},
    "tea": {"id": 378, "categories": ["hot"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "iced tea": {"id": 379, "categories": ["cold"], "meal_type": "snack", "glycemic_index": 0, "carbs": 0, "sugar": 0},
    "boba": {"id": 380, "categories": ["cold", "sweet"], "meal_type": "snack", "glycemic_index": 70, "carbs": 60, "sugar": 40},
    "bubble tea": {"id": 381, "categories": ["cold", "sweet"], "meal_type": "snack", "glycemic_index": 70, "carbs": 60, "sugar": 40},
    "hot chocolate": {"id": 382, "categories": ["hot", "sweet", "creamy"], "meal_type": "snack", "glycemic_index": 50, "carbs": 25, "sugar": 20},
    "hot cocoa": {"id": 383, "categories": ["hot", "sweet", "creamy"], "meal_type": "snack", "glycemic_index": 50, "carbs": 25, "sugar": 20},
    "juice": {"id": 384, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 50, "carbs": 25, "sugar": 20},
    "orange juice": {"id": 385, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 50, "carbs": 25, "sugar": 20},
    "apple juice": {"id": 386, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 40, "carbs": 28, "sugar": 24},
    "lemonade": {"id": 387, "categories": ["sweet", "sour", "cold"], "meal_type": "snack", "glycemic_index": 55, "carbs": 30, "sugar": 28},
    "soda": {"id": 388, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 60, "carbs": 39, "sugar": 39},
    "coke": {"id": 389, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 60, "carbs": 39, "sugar": 39},
    "sprite": {"id": 390, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 60, "carbs": 38, "sugar": 38},
    "ginger ale": {"id": 391, "categories": ["sweet", "cold"], "meal_type": "snack", "glycemic_index": 60, "carbs": 36, "sugar": 35},

    # ==================== VEGETABLES ====================
    "vegetables": {"id": 392, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 5, "sugar": 2},
    "veggies": {"id": 393, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 5, "sugar": 2},
    "broccoli": {"id": 394, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 6, "sugar": 2},
    "carrots": {"id": 395, "categories": ["savory", "crunchy"], "meal_type": "snack", "glycemic_index": 35, "carbs": 10, "sugar": 5},
    "carrot": {"id": 396, "categories": ["savory", "crunchy"], "meal_type": "snack", "glycemic_index": 35, "carbs": 10, "sugar": 5},
    "celery": {"id": 397, "categories": ["crunchy"], "meal_type": "snack", "glycemic_index": 15, "carbs": 3, "sugar": 1},
    "cucumber": {"id": 398, "categories": ["cold", "crunchy"], "meal_type": "snack", "glycemic_index": 15, "carbs": 4, "sugar": 2},
    "tomato": {"id": 399, "categories": ["savory"], "meal_type": "snack", "glycemic_index": 15, "carbs": 4, "sugar": 3},
    "tomatoes": {"id": 400, "categories": ["savory"], "meal_type": "snack", "glycemic_index": 15, "carbs": 4, "sugar": 3},
    "lettuce": {"id": 401, "categories": ["cold"], "meal_type": "lunch", "glycemic_index": 10, "carbs": 3, "sugar": 1},
    "spinach": {"id": 402, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 15, "carbs": 4, "sugar": 0},
    "kale": {"id": 403, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 15, "carbs": 6, "sugar": 0},
    "corn": {"id": 404, "categories": ["sweet", "savory"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 19, "sugar": 6},
    "corn on the cob": {"id": 405, "categories": ["sweet", "savory", "hot"], "meal_type": "dinner", "glycemic_index": 55, "carbs": 19, "sugar": 6},
    "peas": {"id": 406, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 50, "carbs": 14, "sugar": 6},
    "green beans": {"id": 407, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 30, "carbs": 7, "sugar": 3},
    "asparagus": {"id": 408, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 4, "sugar": 2},
    "zucchini": {"id": 409, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 3, "sugar": 2},
    "eggplant": {"id": 410, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 6, "sugar": 3},
    "mushrooms": {"id": 411, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 3, "sugar": 2},
    "mushroom": {"id": 412, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 3, "sugar": 2},
    "onion": {"id": 413, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 9, "sugar": 4},
    "onions": {"id": 414, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 9, "sugar": 4},
    "peppers": {"id": 415, "categories": ["savory", "crunchy"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 6, "sugar": 4},
    "bell pepper": {"id": 416, "categories": ["savory", "crunchy"], "meal_type": "dinner", "glycemic_index": 15, "carbs": 6, "sugar": 4},
    "potato": {"id": 417, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 78, "carbs": 37, "sugar": 2},
    "potatoes": {"id": 418, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 78, "carbs": 37, "sugar": 2},
    "baked potato": {"id": 419, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 78, "carbs": 37, "sugar": 2},
    "mashed potatoes": {"id": 420, "categories": ["savory", "hot", "creamy"], "meal_type": "dinner", "glycemic_index": 80, "carbs": 35, "sugar": 2},
    "sweet potato": {"id": 421, "categories": ["sweet", "hot"], "meal_type": "dinner", "glycemic_index": 63, "carbs": 20, "sugar": 4},
    "avocado": {"id": 422, "categories": ["creamy"], "meal_type": "snack", "glycemic_index": 15, "carbs": 9, "sugar": 0},
    "hummus": {"id": 423, "categories": ["savory", "creamy"], "meal_type": "snack", "glycemic_index": 12, "carbs": 14, "sugar": 0},

    # ==================== MISC ====================
    "bread": {"id": 424, "categories": ["savory"], "meal_type": "snack", "glycemic_index": 75, "carbs": 15, "sugar": 1},
    "baguette": {"id": 425, "categories": ["savory", "crunchy"], "meal_type": "snack", "glycemic_index": 95, "carbs": 15, "sugar": 1},
    "sourdough": {"id": 426, "categories": ["savory"], "meal_type": "snack", "glycemic_index": 54, "carbs": 15, "sugar": 1},
    "rolls": {"id": 427, "categories": ["savory"], "meal_type": "dinner", "glycemic_index": 73, "carbs": 20, "sugar": 2},
    "dinner rolls": {"id": 428, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 73, "carbs": 20, "sugar": 2},
    "naan": {"id": 429, "categories": ["savory", "hot"], "meal_type": "dinner", "glycemic_index": 75, "carbs": 45, "sugar": 3},
    "tortilla": {"id": 430, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 52, "carbs": 24, "sugar": 1},
    "flatbread": {"id": 431, "categories": ["savory"], "meal_type": "lunch", "glycemic_index": 70, "carbs": 30, "sugar": 1},
    "bruschetta": {"id": 432, "categories": ["savory", "crunchy"], "meal_type": "snack", "glycemic_index": 70, "carbs": 20, "sugar": 2},
    "crostini": {"id": 433, "categories": ["savory", "crunchy"], "meal_type": "snack", "glycemic_index": 70, "carbs": 15, "sugar": 1},
}


## CATEGORY KEYWORDS ##
CATEGORY_KEYWORDS = {
    "sweet": ["sweet", "sugary", "dessert"],
    "salty": ["salty", "savory", "umami"],
    "sour": ["sour", "tangy", "tart"],
    "crunchy": ["crunchy", "crispy", "crisp"],
    "creamy": ["creamy", "smooth", "rich"],
    "cold": ["cold", "frozen", "icy", "cool"],
    "hot": ["hot", "warm", "heated"],
    "savory": ["savory", "hearty", "filling"],
    "spicy": ["spicy", "hot", "fiery"],
}

## MEAL TYPE KEYWORDS ##

MEAL_TYPE_KEYWORDS = {
    "snack": ["snack", "bite", "nibble", "munch", "quick bite"],
    "breakfast": ["breakfast", "morning", "brunch"],
    "lunch": ["lunch", "midday", "noon"],
    "dinner": ["dinner", "supper", "evening meal"],
    "dessert": ["dessert", "after dinner", "sweet treat"],
}

## INTENSITY KEYWORDS ##

INTENSITY_KEYWORDS = {
    "high": ["really", "badly", "so much", "dying for", "must have", "desperate", "craving so hard"],
    "low": ["maybe", "kind of", "sort of", "might", "could go for", "wouldn't mind"],
}
